# -*- coding: utf-8 -*-
"""BOOK RECOMENDATION SYSTEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qgn1Bds-eHoZrXFyQvanQlm19ggnHdtD
"""

# Install libraries
!pip install -q kaggle

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from scipy.sparse import csr_matrix

plt.rcParams['figure.figsize'] = (12, 5)
plt.rcParams['font.size'] = 12
sns.set_style('whitegrid')

print('✅ All libraries imported successfully!')

# 2. Upload kaggle.json when prompted

from google.colab import files
files.upload()

# upload kaggle.json
!mkdir -p ~/.kaggle && cp kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d rxsraghavagrawal/book-recommender-system --unzip

print('kaggle.json')

# Load all three datasets


books   = pd.read_csv('BX-Books.csv',        sep=';', encoding='latin-1',
                       on_bad_lines='skip', low_memory=False)
users   = pd.read_csv('BX-Users.csv',         sep=';', encoding='latin-1',
                       on_bad_lines='skip')
ratings = pd.read_csv('BX-Book-Ratings.csv',  sep=';', encoding='latin-1',
                       on_bad_lines='skip')

print(f'📖 Books   : {books.shape}')
print(f'👤 Users   : {users.shape}')
print(f'⭐ Ratings : {ratings.shape}')

# Preview Books dataset
print('=== BOOKS ===')
display(books.head(3))
print(books.dtypes)
print('\nMissing values:\n', books.isnull().sum())

#Preview Users dataset
print('=== USERS ===')
display(users.head(3))
print(users.dtypes)
print('\nMissing values:\n', users.isnull().sum())

# Preview Ratings dataset
print('=== RATINGS ===')
display(ratings.head(3))
print('\nRating value counts (0 = implicit; 1-10 = explicit):')
print(ratings['Book-Rating'].value_counts().sort_index())

# Data cleaning and processing
# 3a. Standardise column names
books.columns   = ['ISBN','Title','Author','Year','Publisher',
                    'ImageS','ImageM','ImageL']
users.columns   = ['UserID','Location','Age']
ratings.columns = ['UserID','ISBN','Rating']

print('Columns renamed ✅')

# 3b. Fix Year-Of-Publication
books['Year'] = pd.to_numeric(books['Year'], errors='coerce')
# Keep only plausible years (printed books)
books = books[(books['Year'] >= 1000) & (books['Year'] <= 2024)]
books['Year'] = books['Year'].astype(int)

print(f'Books after year filter: {books.shape}')

#  3c. Fix Age in Users
users['Age'] = pd.to_numeric(users['Age'], errors='coerce')
# Ages outside 5-90 are likely data entry errors — set to NaN
users.loc[(users['Age'] < 5) | (users['Age'] > 90), 'Age'] = np.nan

print('Age distribution after cleaning:')
print(users['Age'].describe())

#  3d. Remove implicit ratings (Rating == 0)
# Rating=0 means the user interacted but did NOT rate — no preference signal
ratings_explicit = ratings[ratings['Rating'] > 0].copy()
print(f'Ratings before: {len(ratings):,}  |  After removing 0s: {len(ratings_explicit):,}')

# 3e. Filter active users and popular books
# Users who rated < 20 books provide insufficient data for collaborative filtering
user_counts = ratings_explicit['UserID'].value_counts()
active_users = user_counts[user_counts >= 20].index

# Books with fewer than 50 ratings are too obscure for reliable recommendations
book_counts = ratings_explicit['ISBN'].value_counts()
popular_books = book_counts[book_counts >= 50].index

filtered_ratings = ratings_explicit[
    ratings_explicit['UserID'].isin(active_users) &
    ratings_explicit['ISBN'].isin(popular_books)
].copy()

print(f'Filtered ratings : {filtered_ratings.shape}')
print(f'Unique users     : {filtered_ratings["UserID"].nunique():,}')
print(f'Unique books     : {filtered_ratings["ISBN"].nunique():,}')

#  3f. Merge ratings with book metadata
df = filtered_ratings.merge(books[['ISBN','Title','Author','Year','Publisher']],
                             on='ISBN', how='left')
df.dropna(subset=['Title'], inplace=True)

print(f'Merged dataframe shape: {df.shape}')
display(df.head())

#STEP 4 ; EXPLOLATORY DATA ANALYSIS (EDA)

# 4a. Rating distribution
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# All explicit ratings
ratings_explicit['Rating'].value_counts().sort_index().plot(
    kind='bar', ax=axes[0], color='steelblue', edgecolor='white')
axes[0].set_title('All Explicit Ratings Distribution')
axes[0].set_xlabel('Rating (1–10)')
axes[0].set_ylabel('Count')

# Filtered ratings
filtered_ratings['Rating'].value_counts().sort_index().plot(
    kind='bar', ax=axes[1], color='coral', edgecolor='white')
axes[1].set_title('Filtered Ratings Distribution (Active Users + Popular Books)')
axes[1].set_xlabel('Rating (1–10)')
axes[1].set_ylabel('Count')

plt.tight_layout()
plt.show()

#  4b. Top 15 most-rated books
top_books = (df.groupby('Title')['Rating']
               .count()
               .sort_values(ascending=False)
               .head(15))

plt.figure(figsize=(12, 6))
sns.barplot(x=top_books.values, y=top_books.index, palette='viridis')
plt.title('Top 15 Most-Rated Books')
plt.xlabel('Number of Ratings')
plt.ylabel('')
plt.tight_layout()
plt.show()

# 4c. Top 10 authors by number of ratings
top_authors = (df.groupby('Author')['Rating']
                 .count()
                 .sort_values(ascending=False)
                 .head(10))

plt.figure(figsize=(12, 5))
sns.barplot(x=top_authors.values, y=top_authors.index, palette='magma')
plt.title('Top 10 Authors by Total Ratings')
plt.xlabel('Number of Ratings')
plt.ylabel('')
plt.tight_layout()
plt.show()

# 4d. Ratings per user (activity spread)
user_activity = df.groupby('UserID')['Rating'].count()

plt.figure(figsize=(10, 4))
plt.hist(user_activity, bins=50, color='teal', edgecolor='white')
plt.title('Distribution of Ratings per User')
plt.xlabel('Number of Ratings per User')
plt.ylabel('Number of Users')
plt.yscale('log')
plt.tight_layout()
plt.show()

print(user_activity.describe())

#  4e. Mean rating vs number of ratings per book (bubble chart)
book_stats = df.groupby('Title').agg(
    mean_rating=('Rating', 'mean'),
    rating_count=('Rating', 'count')
).reset_index()

plt.figure(figsize=(10, 5))
plt.scatter(book_stats['rating_count'], book_stats['mean_rating'],
            alpha=0.3, color='purple', edgecolors='none', s=15)
plt.title('Mean Rating vs. Number of Ratings per Book')
plt.xlabel('Number of Ratings')
plt.ylabel('Mean Rating')
plt.tight_layout()
plt.show()

# STEP 5 POPULARITY BASED RECOMENDER
# Aggregate per book
popularity_df = df.groupby('Title').agg(
    mean_rating  = ('Rating', 'mean'),
    rating_count = ('Rating', 'count'),
    Author       = ('Author', 'first'),
    Year         = ('Year', 'first')
).reset_index()

# IMDB-style weighted score
C = popularity_df['mean_rating'].mean()    # global mean
m = popularity_df['rating_count'].quantile(0.70)  # 70th percentile as min threshold

def weighted_score(row, m=m, C=C):
    v = row['rating_count']
    R = row['mean_rating']
    return (v / (v + m)) * R + (m / (v + m)) * C

popularity_df['score'] = popularity_df.apply(weighted_score, axis=1)

# Filter to books with enough ratings
popular = popularity_df[popularity_df['rating_count'] >= m].copy()
popular.sort_values('score', ascending=False, inplace=True)

print(f'Global mean rating (C): {C:.2f}')
print(f'Minimum votes threshold (m): {m:.0f}')
print(f'\n🏆 Top 10 Popular Books:')
display(popular[['Title','Author','Year','mean_rating','rating_count','score']].head(10))

# Aggregate per book
popularity_df = df.groupby('Title').agg(
    mean_rating  = ('Rating', 'mean'),
    rating_count = ('Rating', 'count'),
    Author       = ('Author', 'first'),
    Year         = ('Year', 'first')
).reset_index()

# IMDB-style weighted score
C = popularity_df['mean_rating'].mean()    # global mean
m = popularity_df['rating_count'].quantile(0.70)  # 70th percentile as min threshold

def weighted_score(row, m=m, C=C):
    v = row['rating_count']
    R = row['mean_rating']
    return (v / (v + m)) * R + (m / (v + m)) * C

popularity_df['score'] = popularity_df.apply(weighted_score, axis=1)

# Filter to books with enough ratings
popular = popularity_df[popularity_df['rating_count'] >= m].copy()
popular.sort_values('score', ascending=False, inplace=True)

print(f'Global mean rating (C): {C:.2f}')
print(f'Minimum votes threshold (m): {m:.0f}')
print(f'\n🏆 Top 10 Popular Books:')
display(popular[['Title','Author','Year','mean_rating','rating_count','score']].head(10))

# STEP 6 ; COLLABORATIVE FILTERING WITH K-NEAREST NEIGHBOURS )KNN()
#  6a. Build User-Item pivot table
# Rows = book titles, Columns = user IDs, Values = rating
pivot = df.pivot_table(index='Title', columns='UserID', values='Rating')
pivot.fillna(0, inplace=True)

print(f'Pivot table shape: {pivot.shape}  (books × users)')

#6b. Convert to sparse matrix (memory-efficient)
# Most ratings are 0, so sparse format only stores non-zero values
sparse_matrix = csr_matrix(pivot.values)

print(f'Sparse matrix shape : {sparse_matrix.shape}')
print(f'Non-zero elements   : {sparse_matrix.nnz:,}')
print(f'Sparsity            : {1 - sparse_matrix.nnz / (sparse_matrix.shape[0] * sparse_matrix.shape[1]):.2%}')

#  6c. Fit the KNN model
# algorithm='brute' computes exact distances; metric='cosine' measures direction similarity
knn_model = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=10, n_jobs=-1)
knn_model.fit(sparse_matrix)

print('✅ KNN model fitted!')

#  6d. Recommendation function
def get_recommendations(book_title, n_recommendations=5):
    """
    Given a book title, return the n most similar books using KNN.

    Parameters:
        book_title (str): Exact or partial book title
        n_recommendations (int): Number of books to recommend

    Returns:
        DataFrame with recommended books and similarity scores
    """
    # Fuzzy-match: find the closest title in our index
    matches = [t for t in pivot.index if book_title.lower() in t.lower()]
    if not matches:
        print(f"❌ No book found matching '{book_title}'. Try a different title.")
        return None

    matched_title = matches[0]
    print(f"🔍 Finding books similar to: '{matched_title}'\n")

    # Get the book's row index in the pivot table
    book_idx = pivot.index.get_loc(matched_title)

    # Query the KNN model (returns distances and indices)
    distances, indices = knn_model.kneighbors(
        sparse_matrix[book_idx],
        n_neighbors=n_recommendations + 1  # +1 because the book itself is returned
    )

    # Build results dataframe (skip index 0 = the book itself)
    results = []
    for i, idx in enumerate(indices.flatten()[1:]):
        rec_title = pivot.index[idx]
        similarity = 1 - distances.flatten()[i + 1]  # cosine similarity = 1 - cosine distance
        author = df[df['Title'] == rec_title]['Author'].iloc[0] if rec_title in df['Title'].values else 'N/A'
        results.append({'Rank': i+1, 'Title': rec_title, 'Author': author, 'Similarity': round(similarity, 4)})

    return pd.DataFrame(results)


print('✅ Recommendation function defined!')

#  6e. Test the recommender
# Try any book in the dataset — partial matches work!
recommendations = get_recommendations('Harry Potter', n_recommendations=5)
if recommendations is not None:
    display(recommendations)

#Step 7 — Dimensionality Reduction & Clustering (PCA + KMeans)
# 7a. Reduce dimensions with PCA
# Start with 50 components to capture most variance before clustering
pca50 = PCA(n_components=50, random_state=42)
book_vectors_50 = pca50.fit_transform(pivot.values)

print(f'Explained variance (50 components): {pca50.explained_variance_ratio_.sum():.2%}')

# Scree plot — how much variance does each component explain?
plt.figure(figsize=(10, 4))
plt.plot(range(1, 51), np.cumsum(pca50.explained_variance_ratio_), marker='o', markersize=3)
plt.title('Cumulative Explained Variance — PCA (50 components)')
plt.xlabel('Number of PCA Components')
plt.ylabel('Cumulative Explained Variance')
plt.axhline(0.8, color='red', linestyle='--', label='80% variance')
plt.legend()
plt.tight_layout()
plt.show()

#  7b. Elbow Method — find optimal number of clusters
# We compute inertia (sum of squared distances to cluster centres) for K=2..15
inertias = []
K_range = range(2, 16)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(book_vectors_50)
    inertias.append(km.inertia_)
    print(f'  K={k}  inertia={km.inertia_:.0f}')

plt.figure(figsize=(10, 4))
plt.plot(K_range, inertias, marker='o', color='steelblue')
plt.title('Elbow Method — Optimal Number of Clusters')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia (WCSS)')
plt.xticks(K_range)
plt.tight_layout()
plt.show()

#  7c. Fit KMeans with chosen K
# Choose K from the elbow above (typically where the curve bends)
OPTIMAL_K = 6  # ← adjust based on your elbow plot

kmeans = KMeans(n_clusters=OPTIMAL_K, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(book_vectors_50)

pivot['Cluster'] = cluster_labels
print(f'Books per cluster:')
print(pd.Series(cluster_labels).value_counts().sort_index())

# 7d. Visualise clusters in 2D (PCA → 2 components)
pca2 = PCA(n_components=2, random_state=42)
book_vectors_2d = pca2.fit_transform(book_vectors_50)

plot_df = pd.DataFrame({
    'PC1': book_vectors_2d[:, 0],
    'PC2': book_vectors_2d[:, 1],
    'Cluster': cluster_labels,
    'Title': pivot.index
})

plt.figure(figsize=(12, 7))
palette = sns.color_palette('tab10', OPTIMAL_K)
for c in range(OPTIMAL_K):
    subset = plot_df[plot_df['Cluster'] == c]
    plt.scatter(subset['PC1'], subset['PC2'],
                label=f'Cluster {c}', alpha=0.5, s=20, color=palette[c])

plt.title(f'Book Clusters in 2D PCA Space (K={OPTIMAL_K})')
plt.xlabel(f'PC1 ({pca2.explained_variance_ratio_[0]:.1%} variance)')
plt.ylabel(f'PC2 ({pca2.explained_variance_ratio_[1]:.1%} variance)')
plt.legend(title='Cluster', bbox_to_anchor=(1.01, 1))
plt.tight_layout()
plt.show()

#  7e. Sample top-rated books per cluster
# Merge cluster labels back with book stats to label each cluster
pivot_with_cluster = pivot[['Cluster']].copy().reset_index()
book_cluster_df = pivot_with_cluster.merge(
    book_stats[['Title','mean_rating','rating_count']], on='Title', how='left')

print('Sample of top-rated books in each cluster:\n')
for c in range(OPTIMAL_K):
    cluster_books = (book_cluster_df[book_cluster_df['Cluster'] == c]
                     .sort_values('mean_rating', ascending=False)
                     .head(3))
    print(f'--- Cluster {c} ---')
    for _, row in cluster_books.iterrows():
        print(f"  📘 {row['Title'][:60]}  (avg rating: {row['mean_rating']:.1f})")
    print()

# STEP 8 ; INTERACTIVE RECOMENDATION DEMO
#  Interactive input
# Change the book_title below to any book in the dataset

book_title = 'The Da Vinci Code'   # ← change this!
n_recs     = 5

recs = get_recommendations(book_title, n_recs)
if recs is not None:
    display(recs)

    # Show which cluster the input book belongs to
    matches = [t for t in pivot.index if book_title.lower() in t.lower()]
    if matches:
        matched = matches[0]
        cluster = pivot.loc[matched, 'Cluster']
        print(f'\n📌 "{matched}" belongs to Cluster {cluster}')

# STEP 9 ; EVALUATION
from sklearn.metrics import silhouette_score

# Silhouette score measures how well each point fits its assigned cluster
# Sample for speed (full computation is slow on large data)
sample_idx = np.random.choice(len(book_vectors_50), size=min(2000, len(book_vectors_50)), replace=False)
sil_score = silhouette_score(book_vectors_50[sample_idx], cluster_labels[sample_idx])

print(f'Silhouette Score (K={OPTIMAL_K}): {sil_score:.4f}')
print()
print('Interpretation:')
print('  > 0.5  → Strong clusters')
print('  0.2–0.5 → Reasonable structure')
print('  < 0.2  → Weak / no structure')

# Average KNN similarity across all books (sample)
n_sample_books = min(200, sparse_matrix.shape[0])
sample_book_idx = np.random.choice(sparse_matrix.shape[0], n_sample_books, replace=False)

all_similarities = []
for idx in sample_book_idx:
    distances, _ = knn_model.kneighbors(sparse_matrix[idx], n_neighbors=6)
    sims = 1 - distances.flatten()[1:]  # exclude self
    all_similarities.extend(sims)

mean_sim = np.mean(all_similarities)
print(f'Average KNN Cosine Similarity (sample of {n_sample_books} books): {mean_sim:.4f}')

plt.figure(figsize=(8, 4))
plt.hist(all_similarities, bins=50, color='mediumseagreen', edgecolor='white')
plt.axvline(mean_sim, color='red', linestyle='--', label=f'Mean: {mean_sim:.3f}')
plt.title('Distribution of KNN Similarity Scores')
plt.xlabel('Cosine Similarity')
plt.ylabel('Frequency')
plt.legend()
plt.tight_layout()
plt.show()